version: '2'
services:
    web-widget:
        image: ochat/ochat-web-widget
        container_name: ochat-web-widget
        ports:
            - '4200:80' # specify port forewarding
    ionic:
        image: ochat/ochat-ionic
        container_name: ochat-ionic
        ports:
            - '8080:80' # specify port forewarding
    cloud-functions:
        image: ochat/ochat-cloud-functions
        container_name: ochat-cloud-functions
